Reorganized tests.

diff --git a/tests/makefile b/tests/makefile
--- a/tests/makefile
+++ b/tests/makefile
@@ -3,9 +3,16 @@
 .SUFFIXES: .gif .rgb
 
 # This is what to do by default
-test: render-regress giffilter-regress gifsponge-regress \
-		gifclrmp-regress giftext-regress gifbuild-regress \
-		giftool-regress gif2raw-regress misc-regress
+test: render-regress \
+	gif2raw-regress \
+	gifbuild-regress \
+	gifclrmp-regress \
+	giffilter-regress \
+	gifinter-regress \
+	gifsponge-regress \
+	giftext-regress \
+	giftool-regress \
+	misc-regress
 	@echo "No output is good news"
 
 rebuild: render-buildregress misc-buildregress \
@@ -35,11 +42,24 @@ render-buildregress:
 		$(UTILS)/gif2rgb -1 -o $${stem}.rgb $${test}; \
 	done
 
+gif2raw-regress:
+	@echo "gif2raw: Checking that it can self-invert."
+	@$(UTILS)/gif2raw <$(PICS)/treescap.gif | $(UTILS)/gif2raw -s 40 40 -p treescap.map | $(UTILS)/gif2rgb | cmp - treescap.rgb
+
+gifbuild-regress:
+	@echo "gifbuild: Checking idempotency on an icon file."
+	@$(UTILS)/gifbuild <$(PICS)/sample.ico | $(UTILS)/gifbuild -d >/tmp/sample-1.ico; $(UTILS)/gifbuild </tmp/sample-1.ico | $(UTILS)/gifbuild -d >/tmp/sample-2.ico; diff -u /tmp/sample-1.ico /tmp/sample-2.ico; rm /tmp/sample-*.ico
+	@echo "gifbuild: Checking idempotency on an animation."
+	@$(UTILS)/gifbuild -d <$(PICS)/fire.gif >/tmp/fire1.ico
+	@$(UTILS)/gifbuild </tmp/fire1.ico >/tmp/fire2.gif
+	@$(UTILS)/gifbuild -d </tmp/fire2.gif >/tmp/fire2.ico
+	@diff -u /tmp/fire1.ico /tmp/fire2.ico
+
 gifclrmp-regress:
 	@for test in $(GIFS); \
 	do \
 	    stem=`basename $${test} | sed -e "s/.gif$$//"`; \
-	    if echo "Checking colormap of $${test}" >&2; \
+	    if echo "gifclrmap: Checking colormap of $${test}" >&2; \
 	    $(UTILS)/gifclrmp <$${test} >/tmp/regress 2>&1; \
 	    then cmp $${stem}.map /tmp/regress; \
 	    else echo "*** Nonzero return status on $${test}!"; exit 1; fi; \
@@ -52,11 +72,49 @@ gifclrmp-buildregress:
 		$(UTILS)/gifclrmp <$${test} >$${stem}.map; \
 	done
 
+giffilter-regress:
+	@for test in $(GIFS); \
+	do \
+	    stem=`basename $${test} | sed -e "s/.gif$$//"`; \
+	    if echo "giffiltr: Testing copy of $${test}" >&2; \
+	    $(UTILS)/giffilter <$${test} | $(UTILS)/gif2rgb >/tmp/regress 2>&1; \
+	    then cmp $${stem}.rgb /tmp/regress; \
+	    else echo "*** Nonzero return status on $${test}!"; exit 1; fi; \
+	done
+	@rm -f /tmp/regress
+
+gifinter-regress:
+	@echo "gifinter: Checking that it de-interlaces correctly."
+	@$(UTILS)/gifinter -s <$(PICS)/treescap-interlaced.gif | $(UTILS)/gif2rgb | cmp - treescap.rgb
+	@echo "gifinter: Checking that it interlaces correctly."
+	@$(UTILS)/gifinter -i <$(PICS)/treescap.gif | $(UTILS)/gif2rgb | cmp - treescap-interlaced.rgb
+
+gifinto-regress:
+	@echo "gifinto: Checking behavior on short files."
+	@rm -f /tmp/giflib.tmp
+	@$(UTILS)/gifinto <$(PICS)/porsche.gif /tmp/giflib.tmp
+	@if test ! -f /tmp/giflib.tmp; then echo "gifinto failed to create a file when it should have."; fi
+	@rm -f /tmp/giflib.tmp
+	@echo "0123456789" | $(UTILS)/gifinto /tmp/giflib.tmp 2>/dev/null
+	@if test -f /tmp/giflib.tmp; then echo "gifinto created a file when it shouldn't have."; fi
+	@rm -f /tmp/giflib.tmp
+
+gifsponge-regress:
+	@for test in $(GIFS); \
+	do \
+	    stem=`basename $${test} | sed -e "s/.gif$$//"`; \
+	    if echo "gifsponge: Testing copy of $${test}" >&2; \
+	    $(UTILS)/gifsponge <$${test} | $(UTILS)/gif2rgb >/tmp/regress 2>&1; \
+	    then cmp $${stem}.rgb /tmp/regress; \
+	    else echo "*** Nonzero return status on $${test}!"; exit 1; fi; \
+	done
+	@rm -f /tmp/regress
+
 giftext-regress:
 	@for test in $(GIFS); \
 	do \
 	    stem=`basename $${test} | sed -e "s/.gif$$//"`; \
-	    if echo "Checking text dump of $${test}" >&2; \
+	    if echo "giftext: Checking text dump of $${test}" >&2; \
 	    $(UTILS)/giftext <$${test} >/tmp/regress 2>&1; \
 	    then diff -u $${stem}.dmp /tmp/regress; \
 	    else echo "*** Nonzero return status on $${test}!"; exit 1; fi; \
@@ -69,67 +127,20 @@ giftext-buildregress:
 		$(UTILS)/giftext <$${test} >$${stem}.dmp; \
 	done
 
-giffilter-regress:
-	@for test in $(GIFS); \
-	do \
-	    stem=`basename $${test} | sed -e "s/.gif$$//"`; \
-	    if echo "Testing giffilter copy of $${test}" >&2; \
-	    $(UTILS)/giffilter <$${test} | $(UTILS)/gif2rgb >/tmp/regress 2>&1; \
-	    then cmp $${stem}.rgb /tmp/regress; \
-	    else echo "*** Nonzero return status on $${test}!"; exit 1; fi; \
-	done
-	@rm -f /tmp/regress
-
-gifsponge-regress:
-	@for test in $(GIFS); \
-	do \
-	    stem=`basename $${test} | sed -e "s/.gif$$//"`; \
-	    if echo "Testing gifsponge copy of $${test}" >&2; \
-	    $(UTILS)/gifsponge <$${test} | $(UTILS)/gif2rgb >/tmp/regress 2>&1; \
-	    then cmp $${stem}.rgb /tmp/regress; \
-	    else echo "*** Nonzero return status on $${test}!"; exit 1; fi; \
-	done
-	@rm -f /tmp/regress
-
-gifbuild-regress:
-	@echo "Checking idempotency of gifbuild on an icon file."
-	@$(UTILS)/gifbuild <$(PICS)/sample.ico | $(UTILS)/gifbuild -d >/tmp/sample-1.ico; $(UTILS)/gifbuild </tmp/sample-1.ico | $(UTILS)/gifbuild -d >/tmp/sample-2.ico; diff -u /tmp/sample-1.ico /tmp/sample-2.ico; rm /tmp/sample-*.ico
-	@echo "Checking idempotency of gifbuild on an animation."
-	@$(UTILS)/gifbuild -d <$(PICS)/fire.gif >/tmp/fire1.ico
-	@$(UTILS)/gifbuild </tmp/fire1.ico >/tmp/fire2.gif
-	@$(UTILS)/gifbuild -d </tmp/fire2.gif >/tmp/fire2.ico
-	@diff -u /tmp/fire1.ico /tmp/fire2.ico
-
 giftool-regress:
-	@echo "Checking that expensive copy via giftool is faithful."
+	@echo "giftool: Checking that expensive copy via giftool is faithful."
 	@$(UTILS)/giftool <$(PICS)/gifgrid.gif | $(UTILS)/gif2rgb | cmp - gifgrid.rgb
-	@echo "Checking that giftool de-interlaces correctly."
+	@echo "giftool: Checking that it de-interlaces correctly."
 	@$(UTILS)/giftool -i on <$(PICS)/treescap-interlaced.gif | $(UTILS)/gif2rgb | cmp - treescap.rgb
-	@echo "Checking that giftool interlaces correctly."
+	@echo "giftool: Checking that it interlaces correctly."
 	@$(UTILS)/giftool -i off <$(PICS)/treescap.gif | $(UTILS)/gif2rgb | cmp - treescap-interlaced.rgb
-
-gif2raw-regress:
-	@echo "Checking that gif2raw can self-invert."
-	@$(UTILS)/gif2raw <$(PICS)/treescap.gif | $(UTILS)/gif2raw -s 40 40 -p treescap.map | $(UTILS)/gif2rgb | cmp - treescap.rgb
 
 misc-buildregress:
 	$(UTILS)/gifwedge >wedge.gif
 	$(UTILS)/gifpos -s 680 480 <$(PICS)/treescap.gif | $(UTILS)/gifbuild -d >treescap.ico
 
 misc-regress:
-	@echo "Checking wedge generation."
+	@echo "gifwedge: Checking wedge generation."
 	@$(UTILS)/gifwedge | cmp - wedge.gif
-	@echo "Checking that gifinter de-interlaces correctly."
-	@$(UTILS)/gifinter -s <$(PICS)/treescap-interlaced.gif | $(UTILS)/gif2rgb | cmp - treescap.rgb
-	@echo "Checking that gifinter interlaces correctly."
-	@$(UTILS)/gifinter -i <$(PICS)/treescap.gif | $(UTILS)/gif2rgb | cmp - treescap-interlaced.rgb
-	@echo "Checking behavior of gifinto."
-	@rm -f /tmp/giflib.tmp
-	@$(UTILS)/gifinto <$(PICS)/porsche.gif /tmp/giflib.tmp
-	@if test ! -f /tmp/giflib.tmp; then echo "gifinto failed to create a file when it should have."; fi
-	@rm -f /tmp/giflib.tmp
-	@echo "0123456789" | $(UTILS)/gifinto /tmp/giflib.tmp 2>/dev/null
-	@if test -f /tmp/giflib.tmp; then echo "gifinto created a file when it shouldn't have."; fi
-	@rm -f /tmp/giflib.tmp
-	@echo "Checking behavior of gifpos."
+	@echo "gifpos: Checking behavior of gifpos."
 	@$(UTILS)/gifpos -s 680 480 <$(PICS)/treescap.gif | $(UTILS)/gifbuild -d | diff -u treescap.ico -
